hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/paper_multimodal_test_phase"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_biomedclip-vit-base_224_lr0.0001"
  
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/breast_cancer_multimodal_paper/biomedclip-vit-base_combined_image_tabular_classifier"

  dataset: [
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"]
  ]
  datadir: [[None], [None], [None]]
  data_type: "image_tabular"
  tab_to_text: True
  
  image_size: 224

  model_name: "open_clip"
  pretrain_model_name: "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
  drop_rate: 0.7

  freeze_backbone: False
  
  ckpts_list: [
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/1417639_2023-10-25 10:08:18/seed_42/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/1417639_2023-10-25 10:08:18/seed_0/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/1417639_2023-10-25 10:08:18/seed_1/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/1417639_2023-10-25 10:08:18/seed_1234/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/1417639_2023-10-25 10:08:18/seed_3407/best_state.pkl"
  ]

  njobs: 4
  batch_size: 64


  log_freq_eps: 1
