hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/paper_multimodal_test_phase"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_biomedclip-v3-vit-base_224_lr0.01_freeze-backbone"
  
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/breast_cancer_multimodal_paper/biomedclip-vit-base_combined_image_tabular_classifier"

  dataset: [
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"]
  ]
  datadir: [[None], [None], [None]]
  data_type: "image_tabular"
  tab_to_text: True
  group_age: null
  
  image_size: 224

  model_name: "open_clip"
  pretrain_model_name: "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
  drop_rate: 0.7

  freeze_backbone: True
  
  ckpts_list: [
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/630193_2024-08-12 10:23:58/seed_42/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/630193_2024-08-12 10:23:58/seed_0/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/630193_2024-08-12 10:23:58/seed_1/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/630193_2024-08-12 10:23:58/seed_1234/best_state.pkl",    
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/biomedclip-vit-base_combined_image_tabular_classifier/630193_2024-08-12 10:23:58/seed_3407/best_state.pkl",
  ]

  njobs: 4
  batch_size: 64


  log_freq_eps: 1
