hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/paper_multimodal_test_phase"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_vit_large_openai_224_lr0.01_freeze-backbone"
  
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/breast_cancer_multimodal_paper/vit-large-openai_combined_image_tabular_classifier"

  dataset: [
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"]
  ]
  datadir: [[None], [None], [None]]
  data_type: "image_tabular"
  tab_to_text: False
  
  image_size: 224

  model_name: "fusion_vit_large"
  img_model: "vit_large_patch14_clip_224.openai"
  pretrained: True
  drop_rate: 0.7
  drop_path_rate: 0.4
  freeze_backbone: True
  
  ckpts_list: [
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier/739535_2023-10-20 19:48:41/seed_42/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier/739535_2023-10-20 19:48:41/seed_0/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier/739535_2023-10-20 19:48:41/seed_1/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier/739535_2023-10-20 19:48:41/seed_1234/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier/739535_2023-10-20 19:48:41/seed_3407/best_state.pkl"
  ]

  njobs: 4
  batch_size: 64


  log_freq_eps: 1
