hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/paper_multimodal_test_phase"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_vit_base_224_lr0.0001"
  
  combine_crossval: False

  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/breast_cancer_multimodal_paper/vit-base_combined_image_tabular_classifier"

  dataset: [
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"], 
    ["CBIS-DDSM-tfds-with-tabular-2classes"]
  ]
  datadir: [[None], [None], [None]]
  data_type: "image_tabular"
  tab_to_text: False
  group_age: null
  
  image_size: 224

  model_name: "fusion_vit_base"
  img_model: "vit_base_patch16_clip_224.laion2b"
  pretrained: True
  drop_rate: 0.7
  drop_path_rate: 0.4
  freeze_backbone: False
  
  ckpts_list: [
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-base_combined_image_tabular_classifier/713513_2023-10-20 15:09:29/seed_42/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-base_combined_image_tabular_classifier/713513_2023-10-20 15:09:29/seed_0/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-base_combined_image_tabular_classifier/713513_2023-10-20 15:09:29/seed_1/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-base_combined_image_tabular_classifier/713513_2023-10-20 15:09:29/seed_1234/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-base_combined_image_tabular_classifier/713513_2023-10-20 15:09:29/seed_3407/best_state.pkl"
  ]

  njobs: 4
  batch_size: 64


  log_freq_eps: 1
