hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/breast_cancer_base_image_tabular"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_vit_large_224_freeze-backbone"
  trial_runs: {
    "enable": True
  }
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-large_combined_image_tabular_classifier"

  distributed_mode: 'DDP'
  mixed_precision: 'fp16'

  dataset: [
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
  ]
  datadir: [[None], [None], [None]]
  data_type: "image_tabular"
  tab_to_text: False
  
  image_size: 224

  find_unused_parameters: True
  model_name: "fusion_vit_large"
  freeze_backbone: True
  pretrained: True
  drop_rate: 0.7
  drop_path_rate: 0.4
  
  
  resume_ckpt: null
  pretrain_ckpt: null
  num_epochs: 20
  warmup_eps: 2
  njobs: 4
  batch_size: 64
  use_weighted_classes: False
  balanced_sampling: False

  loss: "cross-entropy"
  opt: "Adam"

  log_freq_eps: 1
