hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/breast_cancer_base_image_tabular"
  experiment_name: "ddsm-2classes-image-tabular-classifier"
  run_desc: "fusion_evaclip-vit-giant-plus_224_lr0.01_freeze-backbone"
  trial_runs: {
    "enable": True,
    "random_seeds": [42, 0, 1, 1234, 3407]
  }
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/evalclip-vit-giant-plus_combined_image_tabular_classifier"

  distributed_mode: 'DDP'
  mixed_precision: 'fp16'

  seed: 42

  dataset: [
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
      ["CBIS-DDSM-tfds-with-tabular-2classes"],
  ]
  datadir: [[None], [None], [None]]
  
  dataset_partition: [['train'], ['val'], ['test']]

  kfolds_train_split: {
    "enable": False,
    "k_folds": 2,
    "seed": 42
  }  
  
  data_type: "image_tabular"
  collate_fn: "breast_cancer_patch_tabular"
  tab_to_text: True
  transform: None
  group_age: null
  
  image_size: 224

  find_unused_parameters: True
  model_name: "open_clip"
  pretrain_model_name: 'EVA01-g-14-plus'
  pretrain_data: 'merged2b_s11b_b114k'
  freeze_backbone: True
  
  drop_rate: 0.7
  
  resume_ckpt: null
  pretrain_ckpt: null
  num_epochs: 20
  warmup_eps: 2
  njobs: 4
  batch_size: 64
  lr: 0.01
  use_weighted_classes: False
  balanced_sampling: False

  loss: "cross-entropy"
  opt: "Adam"

  log_freq_eps: 1