hyperparams:
  aim_repo: "/home/hqvo2/Projects/aim_experiments/paper_multimodal_test_phase"
  experiment_name: "ddsm-birad3-strain-lval-v2-test-2classes-image-tabular-classifier"
  run_desc: "fusion_vit_giant_224_lr0.01_freeze-backbone"
  
  combine_crossval: False
  
  save_root:  "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/breast_cancer_multimodal_paper/vit-giant_combined_image_tabular_classifier"
  
  dataset: [
      ["CBIS-DDSM-tfds-with-tabular-2classes-birad3"],
      ["CBIS-DDSM-tfds-with-tabular-2classes-birad3"],
      ["CBIS-DDSM-tfds-with-tabular-2classes-birad3"],
  ]
  datadir: [[None], [None], [None]]
  dataset_partition: [['train'], ['val'], ['test']]

  kfolds_train_split: {
    "enable": True,
    "k_folds": 2,
    "seed": 42
  }
  use_more_data_for_validation: True

  data_type: "image_tabular"
  collate_fn: null
  tab_to_text: False
  group_age: null
  
  image_size: 224

  model_name: "fusion_vit_giant"
  img_model: "vit_giant_patch14_clip_224.laion2b"
  pretrained: True
  drop_rate: 0.7
  drop_path_rate: 0.4
  freeze_backbone: True
  
  ckpts_list: [
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-giant_combined_image_tabular_classifier/766215_2023-12-26 20:06:21/seed_42/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-giant_combined_image_tabular_classifier/766215_2023-12-26 20:06:21/seed_0/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-giant_combined_image_tabular_classifier/766215_2023-12-26 20:06:21/seed_1/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-giant_combined_image_tabular_classifier/766215_2023-12-26 20:06:21/seed_1234/best_state.pkl",
    "/home/hqvo2/Projects/MultiMEDal_multimodal_medical/experiments/vit-giant_combined_image_tabular_classifier/766215_2023-12-26 20:06:21/seed_3407/best_state.pkl"
  ]

  njobs: 4
  batch_size: 64


  log_freq_eps: 1
